### ISSUE TITLE
show options exception

### ISSUE THREAD

**Issue by faitHme000123** [wh1t3p1g/ysomap#23]
![image](https://user-images.githubusercontent.com/6328050/144371276-03e0da58-8e56-41e7-a25c-ce2957a29499.png)
because EvilFileWrapper.getSerializer return null and session.printSessionDetails at line 197 not check

**Comment by wh1t3p1g** [comment]
thx for submit. 
fix at https://github.com/wh1t3p1g/ysomap/commit/79dd5f0ec2bdd2fbbe45ed01ca51e7061283ae78
