### ISSUE TITLE
使用payload生成时提示com.thoughtworks.xstream.converters.ConversionException: Security alert. Marshalling rejected.

### ISSUE THREAD

**Issue by bakabakaba** [wh1t3p1g/ysomap#58]
你好，在使用payload(ImageIO) bullet(JdbcRowSetImplBullet)时报错如下
![image](https://github.com/wh1t3p1g/ysomap/assets/44257329/c092fa47-ea06-4751-b6cf-a4ae0f763d6d)

java版本
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-8u342-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)

**Comment by wh1t3p1g** [comment]
这个是因为项目库xstream用的1.4.10版本，ImageIO用到了javax.crypto下的包，在黑名单里面。可以尝试降低xstream的版本来生成对应内容

**Comment by wh1t3p1g** [comment]
已调整xstream版本，https://github.com/wh1t3p1g/ysomap/commit/23677fc68fe7dc285ca1c26490b7b5145946eefb
